# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ACTIVATE.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 907)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 581, 921))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.UPLODEVIDEO = QtWidgets.QPushButton(self.centralwidget)
        self.UPLODEVIDEO.setGeometry(QtCore.QRect(10, 817, 141, 51))
        self.UPLODEVIDEO.setObjectName("UPLODEVIDEO")
        self.BACKTOHOME = QtWidgets.QPushButton(self.centralwidget)
        self.BACKTOHOME.setGeometry(QtCore.QRect(410, 820, 141, 51))
        self.BACKTOHOME.setObjectName("BACKTOHOME")
        self.AI_BUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.AI_BUTTON.setGeometry(QtCore.QRect(10, 750, 141, 51))
        self.AI_BUTTON.setObjectName("AI_BUTTON")
        self.statues = QtWidgets.QTextBrowser(self.centralwidget)
        self.statues.setGeometry(QtCore.QRect(160, 760, 351, 41))
        self.statues.setStyleSheet("QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}")
        self.statues.setObjectName("statues")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.UPLODEVIDEO.setText(_translate("MainWindow", "UPLODE VIDEO"))
        self.BACKTOHOME.setText(_translate("MainWindow", "BACK TO HOME"))
        self.AI_BUTTON.setText(_translate("MainWindow", "AI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
