# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIDEMODE.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 911)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui imges/Your paragraph text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.LISTSHOWIER = QtWidgets.QTextBrowser(self.centralwidget)
        self.LISTSHOWIER.setGeometry(QtCore.QRect(20, 50, 521, 781))
        self.LISTSHOWIER.setStyleSheet("QLineEdit {\n"
"               border: 2px solid #8f8f8f;\n"
"               border-radius: 20px;\n"
"                padding: 10px;\n"
"             font-size: 16px;\n"
"           }")
        self.LISTSHOWIER.setObjectName("LISTSHOWIER")
        self.HOMEPAGEBUTTON = QtWidgets.QPushButton(self.centralwidget)
        self.HOMEPAGEBUTTON.setGeometry(QtCore.QRect(10, 840, 151, 51))
        self.HOMEPAGEBUTTON.setObjectName("HOMEPAGEBUTTON")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HOMEPAGEBUTTON.setText(_translate("MainWindow", "BACK TO HOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
