# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HOME.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 899)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 551, 911))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui imges/Your paragraph text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ACTIVATEMODE = QtWidgets.QPushButton(self.centralwidget)
        self.ACTIVATEMODE.setGeometry(QtCore.QRect(190, 360, 161, 61))
        self.ACTIVATEMODE.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ACTIVATEMODE.setObjectName("ACTIVATEMODE")
        self.GUIDEMODE = QtWidgets.QPushButton(self.centralwidget)
        self.GUIDEMODE.setGeometry(QtCore.QRect(190, 450, 161, 61))
        self.GUIDEMODE.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.GUIDEMODE.setObjectName("GUIDEMODE")
        self.LOGOUT = QtWidgets.QPushButton(self.centralwidget)
        self.LOGOUT.setGeometry(QtCore.QRect(460, 10, 71, 28))
        self.LOGOUT.setStyleSheet("background-color: rgb(92, 144, 255);")
        self.LOGOUT.setObjectName("LOGOUT")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ACTIVATEMODE.setText(_translate("MainWindow", "ACTIVATE MODE"))
        self.GUIDEMODE.setText(_translate("MainWindow", "GUIDE MODE"))
        self.LOGOUT.setText(_translate("MainWindow", "LOGOUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
