# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 908)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 571, 911))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui imges/Your paragraph text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(60, 230, 411, 51))
        self.email.setStyleSheet("QLineEdit {\n"
"               border: 2px solid #8f8f8f;\n"
"               border-radius: 20px;\n"
"                padding: 10px;\n"
"             font-size: 16px;\n"
"           }")
        self.email.setText("")
        self.email.setObjectName("email")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(60, 320, 411, 51))
        self.username.setStyleSheet("QLineEdit {\n"
"               border: 2px solid #8f8f8f;\n"
"               border-radius: 20px;\n"
"                padding: 10px;\n"
"             font-size: 16px;\n"
"           }")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(60, 410, 411, 51))
        self.password.setStyleSheet("QLineEdit {\n"
"               border: 2px solid #8f8f8f;\n"
"               border-radius: 20px;\n"
"                padding: 10px;\n"
"             font-size: 16px;\n"
"           }")
        self.password.setText("")
        self.password.setObjectName("password")
        self.reenetrpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.reenetrpassword.setGeometry(QtCore.QRect(60, 490, 411, 51))
        self.reenetrpassword.setStyleSheet("QLineEdit {\n"
"               border: 2px solid #8f8f8f;\n"
"               border-radius: 20px;\n"
"                padding: 10px;\n"
"             font-size: 16px;\n"
"           }")
        self.reenetrpassword.setText("")
        self.reenetrpassword.setObjectName("reenetrpassword")
        self.bsignup = QtWidgets.QPushButton(self.centralwidget)
        self.bsignup.setGeometry(QtCore.QRect(190, 560, 131, 51))
        self.bsignup.setStyleSheet("QLineEdit {\n"
"                border: 2px solid #8f8f8f;\n"
"                border-radius: 50px;\n"
"                padding: 10px;\n"
"                font-size: 16px;\n"
"           }")
        self.bsignup.setObjectName("bsignup")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 190, 256, 41))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    border: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(70, 290, 256, 41))
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"    border: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(70, 370, 256, 41))
        self.textBrowser_4.setStyleSheet("QTextBrowser {\n"
"    border: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(70, 460, 256, 41))
        self.textBrowser_5.setStyleSheet("QTextBrowser {\n"
"    border: none;\n"
"}\n"
"\n"
"QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_5.setObjectName("textBrowser_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bsignup.setText(_translate("MainWindow", "Sign up"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">email</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">username</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">password</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">re-enter passowerd</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
