# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'STAGE1CV.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 925)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 601, 971))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui imges/Your paragraph text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 60, 551, 161))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.VIDEOUPLODE = QtWidgets.QPushButton(self.centralwidget)
        self.VIDEOUPLODE.setGeometry(QtCore.QRect(170, 410, 241, 71))
        self.VIDEOUPLODE.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.VIDEOUPLODE.setObjectName("VIDEOUPLODE")
        self.NEXT = QtWidgets.QPushButton(self.centralwidget)
        self.NEXT.setGeometry(QtCore.QRect(422, 797, 111, 41))
        self.NEXT.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.NEXT.setObjectName("NEXT")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">Please record a short introductory video of your child. This video should be between 30 seconds and 1 minute in length. Make sure the recording captures their face and typical expressions. This will help us assess initial observations as part of the autism detection process</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#000000;\">Please record a short introductory video of your child. This video should be between 30 seconds and 1 minute in length. Make sure the recording captures their face and typical expressions. This will help us assess initial observations as part of the autism detection process</span></p></body></html>"))
        self.VIDEOUPLODE.setText(_translate("MainWindow", "uplode the video "))
        self.NEXT.setText(_translate("MainWindow", "NEXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
