# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LOGIN(object):
    def setupUi(self, LOGIN):
        LOGIN.setObjectName("LOGIN")
        LOGIN.resize(553, 904)
        self.centralwidget = QtWidgets.QWidget(LOGIN)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-140, 20, 701, 931))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui imges/Your paragraph text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -70, 531, 341))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui imges/1-Photoroom.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.GUIDEVIDEO = QtWidgets.QPushButton(self.centralwidget)
        self.GUIDEVIDEO.setGeometry(QtCore.QRect(190, 190, 161, 41))
        self.GUIDEVIDEO.setObjectName("GUIDEVIDEO")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 270, 421, 361))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(0, 0, 0);\n"
"                border: 2px solid #8f8f8f;\n"
"                border-radius: 20px;\n"
"                padding: 10px;\n"
"                font-size: 16px;\n"
"            }")
        self.lineEdit.setObjectName("lineEdit")
        self.BLOGIN = QtWidgets.QPushButton(self.centralwidget)
        self.BLOGIN.setGeometry(QtCore.QRect(130, 530, 101, 31))
        self.BLOGIN.setObjectName("BLOGIN")
        self.BSIGNUP = QtWidgets.QPushButton(self.centralwidget)
        self.BSIGNUP.setGeometry(QtCore.QRect(320, 530, 101, 31))
        self.BSIGNUP.setObjectName("BSIGNUP")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 280, 171, 71))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(110, 350, 171, 41))
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.USERNAME = QtWidgets.QLineEdit(self.centralwidget)
        self.USERNAME.setGeometry(QtCore.QRect(110, 380, 351, 41))
        self.USERNAME.setStyleSheet("QLineEdit {\n"
"                border: 2px solid #8f8f8f;\n"
"                border-radius: 20px;\n"
"                padding: 10px;\n"
"                font-size: 16px;\n"
"            }")
        self.USERNAME.setText("")
        self.USERNAME.setObjectName("USERNAME")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(110, 440, 171, 41))
        self.textBrowser_3.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(0, 0, 0);\n"
"    border: none;\n"
"}\n"
"")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.USERNAME_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.USERNAME_2.setGeometry(QtCore.QRect(110, 470, 351, 41))
        self.USERNAME_2.setStyleSheet("QLineEdit {\n"
"                border: 2px solid #8f8f8f;\n"
"                border-radius: 20px;\n"
"                padding: 10px;\n"
"                font-size: 16px;\n"
"            }")
        self.USERNAME_2.setText("")
        self.USERNAME_2.setObjectName("USERNAME_2")
        LOGIN.setCentralWidget(self.centralwidget)

        self.retranslateUi(LOGIN)
        QtCore.QMetaObject.connectSlotsByName(LOGIN)

    def retranslateUi(self, LOGIN):
        _translate = QtCore.QCoreApplication.translate
        LOGIN.setWindowTitle(_translate("LOGIN", "MainWindow"))
        self.GUIDEVIDEO.setText(_translate("LOGIN", "Guide Video"))
        self.BLOGIN.setText(_translate("LOGIN", "Login"))
        self.BSIGNUP.setText(_translate("LOGIN", "Sign Up"))
        self.textBrowser.setHtml(_translate("LOGIN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; color:#ffffff;\">LOGIN</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("LOGIN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">USERNAME</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("LOGIN", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">PASSWORD</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LOGIN = QtWidgets.QMainWindow()
    ui = Ui_LOGIN()
    ui.setupUi(LOGIN)
    LOGIN.show()
    sys.exit(app.exec_())
